<a href="https://colab.research.google.com/github/Vineesha2005/AIML/blob/main/AIML(PART_1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#implementing lists using Numpy
import numpy as np
print(1.1)
list=np.array([[1],[2],[3],[4],[5]])
print(list)

1.1
[[1]
 [2]
 [3]
 [4]
 [5]]


In [ ]:
#implementing arrays using Numpy
import numpy as np
print(1.2)
array=np.array([1,2,3,4,5])
print(array)


1.2
[1 2 3 4 5]


In [ ]:
#Indentifing type using "type"()method
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(type(arr))


<class 'numpy.ndarray'>


In [ ]:
#performing mathematical operations
#1.multipilcation
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
mul=np.multiply(a,b)
print(mul)
#2.division
div=np.divide(a,b)
print(div)
#3,poweroff
power=np.power(a,b)
print(power)

[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [ ]:
#Addition of two array
import numpy as np
array1=np.array([1,2,3])
array2=np.array([4,5,6])
r=array1+array2
print(r)

[5 7 9]


In [ ]:
#implement np.sin(), log(), np.exp(), log2()
import numpy as np
a = np.array([1,2,3])
sin = np.sin(a)
print(sin)
log = np.log(a)
print(log)
exp = np.exp(a)
print(exp)
log2 = np.log2(a)
print(log2)

[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]
[0.        1.        1.5849625]
